# K8s is extensible - we can add in our own custom objects.
# This specifies the set of objects we want K8s to look at
apiVersion: apps/v1
# The type of Object we want to create ie: Pod|Deployment
kind: Deployment
# Config options for the deployment we are about to create
metadata:
  # When the deployment is created, give it a name of event-bus-depl
  name: event-bus-depl
spec:
  # create one instance
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          # because no version suffix, kubernetes presumes latest version
          # After you make code changes, again run docker build -t tverkon/posevent-bus
          # Then run "Kubectl rollout restart deployment tverkon/event-bus" to
          # to deploy your changes
          image: tverkon/event-bus
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  type: ClusterIP
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
